In [16]:
import pandas as pd
import glob, io
import zipfile

zip_files = glob.glob('ncdrisc_data/*.zip')

def read_zip(zip_fn):
    zf = zipfile.ZipFile(zip_fn)
    for fn in zf.namelist():
        print(fn)
        if '.csv' in fn:
            return pd.read_csv(zip_fn)
        elif '.xlsx' in fn:
            return pd.read_excel(zf.open(fn).read())

zip_data = []
for zip_file in zip_files:
    df = read_zip(zip_file)
    print(len(df))
    zip_data.append(df)

NCD-RisC_Nature_2020_Cholesterol_Age-specific_by_Country.csv
234000
NCD_RisC_Lancet_2020_height_child_adolescent_country.csv
210000
NCD_RisC_Nature_2019_female_age_specific_countries.csv
99000
NCD_RisC_Nature_2023_height_child_adolescent_country.xlsx
186000
NCD_RisC_Lancet_2020_BMI_child_adolescent_country.csv
270000
NCD_RisC_Lancet_2017_BMI_female_age_specific_country.csv
126000
NCD_RisC_Nature_2019_male_age_specific_countries.csv
99000
NCD_RisC_Nature_2023_BMI_child_adolescent_country.xlsx
186000
NCD_RisC_Lancet_2017_BMI_male_age_specific_country.csv
126000

In [25]:
zip_data[0]

,Country,Year,Sex,Age group,Mean total cholesterol (mmol/L),Mean total cholesterol lower 95% uncertainty interval (mmol/L),Mean total cholesterol upper 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol (mmol/L),Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L),Mean HDL cholesterol (mmol/L),Mean HDL cholesterol lower 95% uncertainty interval (mmol/L),Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)
0,Afghanistan,1980,Men,18-19,3.938280,3.408243,4.450841,2.390296,1.786243,3.001487,1.203759,0.903827,1.491221
1,Afghanistan,1980,Men,20-24,4.030348,3.461665,4.583069,2.565352,2.025941,3.104508,1.207433,0.912178,1.486294
2,Afghanistan,1980,Men,25-29,4.152129,3.523245,4.771284,2.781679,2.317325,3.244324,1.209319,0.917293,1.482287
3,Afghanistan,1980,Men,30-34,4.257240,3.571934,4.923948,2.955077,2.523206,3.386726,1.209177,0.918113,1.481715
4,Afghanistan,1980,Men,35-39,4.339896,3.612904,5.052363,3.081967,2.652806,3.506228,1.209154,0.917683,1.481755
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233995,Zimbabwe,2018,Women,65-69,4.446930,3.602001,5.318344,3.189870,2.774696,3.605794,1.357039,1.110378,1.598515
233996,Zimbabwe,2018,Women,70-74,4.372726,3.524492,5.258760,3.100383,2.645811,3.550462,1.363841,1.121210,1.604588
233997,Zimbabwe,2018,Women,75-79,4.318492,3.447941,5.235428,3.055181,2.555161,3.552644,1.375915,1.130139,1.623145
233998,Zimbabwe,2018,Women,80-84,4.324823,3.411502,5.281729,3.111651,2.550614,3.680846,1.397937,1.141691,1.658576
233999,Zimbabwe,2018,Women,85plus,4.486063,3.426113,5.574371,3.423853,2.672467,4.172845,1.448101,1.148511,1.752269

In [50]:
csv_files = glob.glob('ncdrisc_data/*United Kingdom.csv')

result = {}
for csv_file in csv_files:
    print('Check', csv_file)
    try:
        csv_df = pd.read_csv(csv_file, on_bad_lines='skip')
        
        for i, zip_df in enumerate(zip_data):
            try:
                merged = zip_df.merge(csv_df, how='left')
                print('csv df:{}\tzip df:{}\tmerged:{}'.format(len(csv_df), len(zip_df), len(merged)))
                if len(merged) == len(zip_df):
                    result[csv_file] = zip_files[i]
                    break
            except:
                continue
    except:
        print('Fail to load', csv_file)
   
print('Matched:', len(result))

Check ncdrisc_data/_dm_individual-countries_United Kingdom.csv
csv df:70	zip df:234000	merged:234000
Check ncdrisc_data/_bmi_height_height_by_country_NCD_RisC_Lancet_2020_height_child_adolescent_United Kingdom.csv
csv df:1050	zip df:210000	merged:210000
Check ncdrisc_data/_chol_individual-countries_United Kingdom.csv
csv df:78	zip df:234000	merged:234000
Check ncdrisc_data/_height_urban-rural_ado_country_NCD_RisC_Nature_2023_height_child_adolescent_country-United Kingdom.csv
Check ncdrisc_data/_bmi_adult_country_NCD_RisC_Lancet_2017_BMI_age_standardised_United Kingdom.csv
Fail to load ncdrisc_data/_bmi_adult_country_NCD_RisC_Lancet_2017_BMI_age_standardised_United Kingdom.csv
Check ncdrisc_data/_bp_individual-countries_United Kingdom.csv
csv df:82	zip df:234000	merged:234000
Check ncdrisc_data/_bmi_height_bmi_by_country_NCD_RisC_Lancet_2020_BMI_child_adolescent_United Kingdom.csv
csv df:1350	zip df:210000	merged:210000
Check ncdrisc_data/_hypertension_Country_files_NCD-RisC_Lancet_2021_Hypertension_United Kingdom.csv
csv df:60	zip df:234000	merged:234000
Check ncdrisc_data/_bmi-urban-rural_NCD_RisC_Nature_2019_age_standardised_country-United Kingdom.csv
csv df:66	zip df:234000	merged:234000
Check ncdrisc_data/_bmi_urban-rural_ado_country_NCD_RisC_Nature_2023_BMI_child_adolescent_country-United Kingdom.csv
Matched: 7

In [51]:
for csv_file in csv_files:
    if csv_file not in result:
        print(csv_file)

ncdrisc_data/_height_urban-rural_ado_country_NCD_RisC_Nature_2023_height_child_adolescent_country-United Kingdom.csv
ncdrisc_data/_bmi_adult_country_NCD_RisC_Lancet_2017_BMI_age_standardised_United Kingdom.csv
ncdrisc_data/_bmi_urban-rural_ado_country_NCD_RisC_Nature_2023_BMI_child_adolescent_country-United Kingdom.csv